services:
  db:
    image: postgres
    restart: always
    networks:
      - pg
    environment:
      POSTGRES_DB: piscineds
      POSTGRES_USER: jgautier
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./data_2022_oct.csv:/tmp/customer/data_2022_oct.csv
      - ./data_2022_nov.csv:/tmp/customer/data_2022_nov.csv

  adminer:
    image: dpage/pgadmin4
    restart: always
    networks:
      - pg
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: jgautier@jgautier.com
      PGADMIN_DEFAULT_PASSWORD: jgautier
    volumes:
      - ./servers.json:/pgadmin4/servers.json

networks:
  pg: