services:
  db:
    image: postgres
    restart: always
    networks:
      - pg
    environment:
      POSTGRES_DB: piscineds
      POSTGRES_USER: jgautier
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - /mnt/nfs/homes/jgautier/sgoinfre/asset/customer:/tmp/customer
      - /mnt/nfs/homes/jgautier/sgoinfre/asset/script/table.sql:/docker-entrypoint-initdb.d/table.sql

  adminer:
    image: dpage/pgadmin4
    restart: always
    networks:
      - pg
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: jgautier@jgautier.com
      PGADMIN_DEFAULT_PASSWORD: jgautier
    volumes:
      - /mnt/nfs/homes/jgautier/sgoinfre/asset/config/servers.json:/pgadmin4/servers.json

networks:
  pg: